name: Build and Deploy
env:
  REMOTE_HOST: '20.203.104.146'
  REMOTE_USER: 'nutrisha'
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
on:
  push:
    branches: [ main ]  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js 22.11.0 and npm 9.8.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'

      - name: Inject OpenAI API Key
        run: |
          # Replace the entire openaiApi declaration
          sed -i "s|const openaiApi = .*|const openaiApi = \"${{ secrets.OPENAI_API_KEY }}\";|" src/environments/environment.ts
          
          # Verify change (shows only the modified line)
          grep -A2 "const openaiApi" src/environments/environment.ts
          
      # - name: Create secret config file
      #   run: |
      #     rm -rf  $GITHUB_WORKSPACE/src/environments/environment.dev.ts
      #     echo "${{ secrets.DEV_SERVER_ENV }}" >  $GITHUB_WORKSPACE/src/environments/environment.dev.ts
      #     cat  $GITHUB_WORKSPACE/src/environments/environment.dev.ts
      #     ls -la  $GITHUB_WORKSPACE/src/environments/
        
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:dev  # Assumes `build` script in package.json

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Deploy dist folder to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/dev/ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:/var/www/frontend/


      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} << 'EOF'
            sudo chown -R nutrisha:www-data /var/www/frontend 
            sudo systemctl restart nginx
          EOF
          
